[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false
showErrorDetails = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

[logger]
level = "info"